### PR TITLE
fix(navigation): use autogenerate fonction to create navigation sidebar

### PR DESCRIPTION
**Pull request by tomalaforge**
add autogenerate to generate navigation sidebar. 

This way you just have to create your file and you do not forget to add it inside the conf.

What do you think?

### CODE REVIEW

**Comment by nartc** [comment]
Does it automatically sort alphabetically?

**Comment by tomalaforge** [comment]
It's order alphabetically depending on the file name, not on the title name. So if the title has the same name as the file, it will work

**Comment by tomer953** [comment]
> Does it automatically sort alphabetically?

Yes :)

**[Sorting](https://starlight.astro.build/reference/configuration/)**
> Autogenerated sidebar groups are sorted by filename alphabetically. For example, a page generated from astro.md would appear above the page for starlight.md.



what about the readme? maybe remove the list? otherwise some CI needed to sort the list there

**Comment by nartc** [comment]
Yeah probably remove the list from readme and just reference the documentation url there

**Comment by tomalaforge** [comment]
What do you mean ? I didn't understand what you want me to do

**Comment by nartc** [comment]
@tomalaforge we can turn on autogenerate for the Astro documentation site. There's another list of utilities in the root `README.md`. @tomer953 and I were talking about removing the list from `README.md` altogether and only add a URL to the documentation site on the `README.md` instead.

**Comment by tomalaforge** [comment]
change made, but I think we can find a better way to express it.

**Review by nartc — APPROVED** [review]
We can always iterate

**Comment by tomer953** [comment]
Please note that the new PR will cause installation to be before introduction.

**Pull request merged**
