### PR TITLE
docs: Categories utilities

### LINKED ISSUE #79: [docs] categorise utils
CleanShot 2023-09-23 at 11 18 22@2x

We need to categorise utils for easier navigation as the list is becoming big!

### PR DESCRIPTION
**Pull request by tomer953**
fix #79 

image

I also included few more fixes

### CODE REVIEW

**Comment by tomalaforge** [comment]
Should all subfolder be unfold ?

**Comment by tomer953** [comment]
> Should all subfolder be unfold ?

by unfold do you mean like showing the contents by default?
imo yes, starlight and other docs I know is expanded by default.
https://starlight.astro.build/getting-started/

(also angular-challanges b.t.w :D)

**Comment by tomalaforge** [comment]
yes it's what I mean. 😅

Yes most docs are extended by default. (and angular challenges indeed) but I don't know if the doc is getting longer, collapsing the folder is maybe a better option to have a better first look, but maybe not. Don't know what's better between scrolling or clicking to expend content

**Review by nartc — APPROVED** [review]
LGTM. Can you rebase?

**Comment by tomer953** [comment]
done

**Pull request merged**
