### PR TITLE
feat(docs): add internationalization to docs

### PR DESCRIPTION
**Pull request by nelsongutidev**
- Adds internationalization to docs
- Adds translation in Spanish to the  landing page and the pages in the following folders:

1. Getting Started
2. Components pages
3. Directives 
4. Forms
5. Gesture
6. Miscellaneous

Addresses https://github.com/nartc/ngxtension-platform/issues/150

### CODE REVIEW

**Review by nartc — APPROVED** [review]
This is a tremendous amount of work. Thank you!

**Comment by nartc** [comment]
@all-contributors please add @nelsongutidev for doc

**Comment by Villanuevand** [comment]
Hey @nelsongutidev @nartc I would like to contribute with this project.

**Comment by nelsongutidev** [comment]
> Hey @nelsongutidev @nartc I would like to contribute in this project.

Yes @Villanuevand ! lets go for it and get all the docs in Spanish! I was about to ping you and @rlmestre about this since you both told me you wanted to help. Will reach out to you offline about this

**Pull request merged**
